### ISSUE TITLE
Errors when using `get` methods without data

### ISSUE THREAD

**Issue by crutchcorn** [couchbaselabs/docker-hapi-node-example#1]
`customers GET` without data gives:
Debug: internal, implementation, error 
    TypeError: Cannot read property '_name' of null

`products GET` without data gives:
Debug: internal, implementation, error 
    TypeError: Cannot read property '_name' of null
   

Something that may affect replication of the bug is that I'm using the Docker that was mentioned in the README

**Comment by nraboy** [comment]
This is related to https://github.com/couchbaselabs/docker-hapi-node-example/issues/3 in that `bucket` is undefined so hence `bucket._name` is going to break.
