### ISSUE TITLE
POST to customer throws server error

### ISSUE THREAD

**Issue by crutchcorn** [couchbaselabs/docker-hapi-node-example#3]
The error I recieve when trying to use the POST to `cusomer` is:
`TypeError: Cannot read property 'insert' of null`

Something that may affect replication of the bug is that I'm using the Docker that was mentioned in the README

**Comment by nraboy** [comment]
A few questions:

Did you wait until the Docker containers were completely started and deployed? The process is not instant. You might see this:

```
Creating sacjsmeetup_database_1 ... done
Creating sacjsmeetup_api_1      ... done
```

The above means that the containers are deployed, but it doesn't mean they have completely started. The Couchbase container gets provisioned in the background and the Node application polls periodically to see if it is ready.

Try running this:

```
$ docker logs -f sacjsmeetup_api_1

Listening at http://752f8de5134a:3000
```

When it says that it is listening, it means it is ready. The endpoints are still available even if it is not ready. This could be further optimized, but it doesn't hurt to wait for around 30 to 60 seconds.

Also, make sure that you don't have a bunch of containers running that might conflict. `ctrl+c` doesn't completely stop a detached container. You'll want to do `docker-compose down`.

**Comment by crutchcorn** [comment]
So, just to make sure I wasn't hitting any errors, I removed the docker containers and reran the `docker-compose up -d` command (after running `git pull` to ensure I had the most recent updates).

The following is the output of that command:
```
crutchcorn@Corbin-Laptop MINGW64 ~/git/talk/server (master)
$ docker-compose up -d
Creating server_api_1      ... done
Creating server_database_1 ... done
```

Running `docker logs -f server_database_1` gave me the following output (I know you weren't asking, just including for the whole story):
```
Starting Couchbase Server -- Web UI available at http://<ip>:8091 and logs available in /opt/couchbase/var/lib/couchbase/logs
{error_logger,{{2018,4,10},{5,54,33}},"global_trace:~n~p",[{loop_the_locker,{multi,[],[],[],'nonode@nohost',false,false}}]}

Waiting for Couchbase Server to start............
Couchbase Server has started
Starting configuration for DEFAULT node
Configuring Individual Node Settings
Configuring Cluster
Setting the Cluster Name
Configuring Auto Failover Settings
Creating example bucket
Creating RBAC user example
Configuring Alert Settings
Configuring Compaction Settings
The new DEFAULT node has been successfully configured
```

However `docker logs -f server_api_1` gave me nothing. That being said, starting Kitematic and viewing the container gave me this:
![image](https://user-images.githubusercontent.com/9100169/38538613-79554cd4-3c49-11e8-99b7-7e6562648d81.png)

Which seems to (me) clearly show the API running in some form.

Just to double check that the bug persisted the clean container, I ran the `POST` command that this bug is refering to with the same results:
![image](https://user-images.githubusercontent.com/9100169/38538709-dce3cc8a-3c49-11e8-9235-a39c8805b39e.png)

**Comment by nraboy** [comment]
@mgroves, can you try to deploy this application on your machine since you use Windows and may have experienced the Hyper-V issue?

@crutchcorn, can you add some `console.log` statements in the `connect()` method. If nothing is being printed on the application container it means it is having trouble connecting to the database. It only prints when it has connected. What is supposed to happen is the `connect()` method is supposed to trigger on an interval until a connection is established. Remember, the database setup is not instant so the Node application should keep trying to connect.

Another thing you can try is spin up the containers separately. For example:

```
docker-compose run -d --service-ports --name database database
docker-compose run -d --service-ports --name api api
```

However, I'm not sure if you need to define the network in that scenario.

**Comment by mgroves** [comment]
Just tried it on my Windows machine, and it seemed to work okay (I live streamed it, so if you want to follow along, it will be on youtube soon).

UPDATE: I was asked to post docker version and hyper-v version

* Docker version 18.03.0-ce, build 0520e24
* Hyper-V Manager says version is 10.0.16299.15 (not sure if that's the same as Hyper-V version)

**Comment by nraboy** [comment]
https://www.twitch.tv/videos/248815153

**Comment by mgroves** [comment]
The twitch video may expire after 30 days, so here's the recording on youtube: https://youtu.be/7N2acFbM92Q

**Comment by crutchcorn** [comment]
Hmm, checking the console logs I'm getting the following:
```
I am in 'connect'
There was an error in connect
{ CouchbaseError: Authentication failed. You may have provided an invalid username/password combination
  message: 'Authentication failed. You may have provided an invalid username/password combination',
  code: 2 } 
```

When modifying the connect function to:
```
var connect = (callback) => {
    console.log("I am in 'connect'");
    if(bucket) {
        return callback();
    }
    cluster = new Couchbase.Cluster("couchbase://" + process.env.COUCHBASE_HOST);
    cluster.authenticate(process.env.COUCHBASE_APPLICATION_USER, process.env.COUCHBASE_APPLICATION_PASSWORD);
    bucket = cluster.openBucket(process.env.COUCHBASE_BUCKET, error => {
        if(error) {
            console.log('There was an error in connect');
            console.log(error);
            bucket = null;
            setTimeout(() => {
                connect(callback);
            }, 5000);
        } else {
            console.log('Calling callback in connect');
            return callback();
        }
    });
}
```

**Comment by crutchcorn** [comment]
You know, I am using Docker Toolbox (because I literally couldn't get Hyper-V working at all)... My thought is that the networking behavior between toolbox and standard Docker is different... Which would make sense...

**Comment by nraboy** [comment]
Ah yes, you would probably need Docker for Windows, not Docker Toolbox. I think Docker Toolbox uses Virtual Box right?

**Comment by crutchcorn** [comment]
That it does. Unfortunately, I really can't get Docker for Windows to work. I spent way too much time on it and I cannot for the life of me figure out how to get it up and running. I guess I'll just do the setup of couchbase myself locally
